version: 1.0.{build}
platform:
  - x86
  - x64

build:
  verbosity: quiet

install:
  - java -version
  - cup all -v
  - cinst -y jdk10
  - refreshenv
  - java -version

build_script:
  - gradlew.bat tasks

test_script:


branches:
  only:
    - master